### ISSUE TITLE
What do we do with artworks without images?

### ISSUE THREAD

**Issue by broskoski** [artsy/force#106]
For instance, https://www.artsy.net/artwork/jacopo-da-pontormo-study-of-a-nude-boy-partial-figure-study-recto-study-of-a-seated-man-verso

**Comment by briansw** [comment]
@broskoski maybe this should be handled in volt? @garrengotthardt thoughts here?

**Comment by alloy** [comment]
@starsirius Can you have a think about this?

**Comment by starsirius** [comment]
In general, we require artworks to have images before publishing by admins; in fact, artworks created in CMS (Volt) should always have images as uploading images is the first step (this artwork was created and published in [2014](https://api.artsy.net/api/v1/artwork/jacopo-da-pontormo-study-of-a-nude-boy-partial-figure-study-recto-study-of-a-seated-man-verso) which predates Volt). So maybe

1. @garrengotthardt and the institutions team can confirm if there is actually a use case for artworks with no images.
1. Otherwise, I think it's a data issue and we should re-upload images for them. Force can probably make that assumption.

**Comment by garrengotthardt** [comment]
hey guys sorry just catching up on this - there is no use case for published works without images, and the GR and instititutions teams dont publish works unless there are images.

Since it looks like theres an image record for this work but the image is missing seems like two possible scenarios could be at play:
1. could be that this work was published in a rush before processing was complete and then it ended up failing — though unlikely here since it seems there is no original to even try to reprocess, or
2. the original image got lost for this when *i think* platform was working on changing storage of original images about 1-1.5 years ago

**Comment by alloy** [comment]
Sounds like we may want to do a sweep then and cleanup the data from Gravity’s end?

/cc @joeyAghion
