### ISSUE TITLE
Difficulty in setting up the FORCE repo - Local & Prod Development Setup

### ISSUE THREAD

**Issue by desaijay315** [artsy/force#11203]
Hi Team,

I have some difficulty in setting up the force project locally, and I am looking forward to contributing to the Force code.

I have followed the below steps as per the [CONTRIBUTING.md](https://github.com/artsy/force/blob/main/CONTRIBUTING.md) guidelines:-

**Local Development setup:-**

1. git clone git@github.com:artsy/force.git && cd force
2. Run ./scripts/setup.sh (for installations and env files setup)
3. yarn start

**Facing below issues:-**

1. Failing auth (**URL** - /API/v1/xapp_token) - Do the client id and secret still valid for the OSS development

![image](https://user-images.githubusercontent.com/9349985/196609174-eae6b396-7245-4880-863a-1aeb9666afb6.png)

2. Module Not found - (src/generated folder)

![Screenshot 2022-10-19 113520](https://user-images.githubusercontent.com/9349985/196609909-69a8ded7-a3a8-45a3-aa82-c11c56f30655.png)

3. Can't see any data due to issue 2 I guess. Let me know if the OSS env (API/Cloudfront images URL) variables values are still valid or require some change.

**Local Production Development:-**

1. Webpack config fails 

![image](https://user-images.githubusercontent.com/9349985/196612651-2a825355-c6f9-4ed2-94a5-9caeb57eb020.png)

**_Note_**: _I added a cross-env package to set the env variables on my window machine._

 Have a few questions about the repo 
1. I see that Redis is being used - Can you please highlight when it caches the data?  (During the load or pre-loading of the page?)
3.  About React-Relay (Have used apollo previously, but new to react relay) - How is the GraphQL (Types and Hooks ) getting automatically generated within the src/generated folder (is this done under the hood by relay-compiler)?  
5. Backend Setup? (any guidelines here)?

Thanks in advance :) Looking forward to your response.

**Comment by erikdstock** [comment]
Hi @desaijay315 - could you please paste the entire error printout from your first image? You can use triple backticks like <code>``` </code> to apply monospaced/code formatting.

Regarding your question number 2, does the command `yarn react-relay` work? It should execute successfully and not say that any files were changed or generated in its output.

Finally, I would say this repository makes some assumptions about your develop environment, including that you are in a MacOS or linux environment. If you are using WSL it's likely there will be some additional setup steps at a minimum.

**Comment by desaijay315** [comment]
Hello @erikdstock - Thanks for your response.

Yes, I am on a windows machine :(

Here's the entire error printed on a gif - Kindly ZOOM-IN to your browser

![Animation](https://user-images.githubusercontent.com/9349985/196767024-b72409d4-351f-43f0-aa76-304c3355f079.gif)

2. yarn run relay 

![image](https://user-images.githubusercontent.com/9349985/196767759-778e8838-2018-4c83-b222-0b272b262f20.png)

**Comment by laurabeth** [comment]
@desaijay315 as a mostly windows user, I can affirm that wsl will be the way to go to ease setup on this project. 

Here is a guide on getting WSL set up in windows:

https://learn.microsoft.com/en-us/windows/wsl/install

**Comment by desaijay315** [comment]
Sure, let me give it a try...:) That might surely work I feel since it
works successfully on macOS and Linux...

**Comment by dblandin** [comment]
Hi @desaijay315,

First of all, thank you for your interest in Artsy and this repository!

At Artsy, we have a long-held [open source by default](https://github.com/artsy/README/blob/main/culture/engineering-principles.md#open-source-by-default) principle. However, that doesn't mean that all of our code is open source. When we keep services/repositories closed source, we have good reasons to do so. By choosing to open source many of our repositories, we gain a lot in return. It's easy for us to share our work with the larger community outside of Artsy. We can refer to specific PRs or code in our blog posts and podcast episodes. And we hope that it's an educational benefit for the larger community outside of Artsy. Interested engineers can browse the code freely. They can even clone the repository and run it locally but since this app relies on services that are closed source, the expectation is that when running Force locally, Force communicates with our hosted staging services.

As that's the case, we do not provide support (nor encourage) to run this application outside of Artsy in a staging/production environment. External use of this repository can be used for educational purposes or the occasional contribution but we don't support running this repository against any self-managed backend services. The documentation we've included so far is provided without guaranteed support from the team. We'll do our best to keep it updated but we unfortunately do not have the capacity to extend much support beyond what we've already documented.

As @erikdstock and @laurabeth suggest, if you're still interested in running this app locally against our staging services, I would recommend switching to one of our supported environments (even if that means running a Virtual Machine on your Windows setup). You might have better luck getting the app to boot up.

Thank you for understanding! 💜

**Comment by desaijay315** [comment]
Hello Devon,

Thank you so much for your response...

I appreciate that the team and company also thinks about the community
overall and that's what brought to me to the Artsy force repo..

I won't be using this to deploy somewhere outside..but checking this repo
only for educational purpose and would love to contribute once I get the
grasp on the project or starting to solve some small issues on the app
initially.




Regards,
JD

**Comment by desaijay315** [comment]
Hello @erikdstock , @laurabeth  - I have now completed the setup on WSL. Thank you for your advice
1 Question - Do we have the cors enabled for localhost:4000?

Getting this error currently
```
Access to fetch at 'https://metaphysics-staging.artsy.net/v2' from origin 'http://localhost:4000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.```

**Comment by dblandin** [comment]
@desaijay315 Can you provide your browser's unique report URL as shown [here on whatismybrowser.com](https://www.whatismybrowser.com/)?

For example, here's mine: https://www.whatismybrowser.com/w/CSJ4YT8

By default, Force is configured to run on port `5000` so I'm surprised that Force booted up with port `4000`. I'd try running `yarn start` again with no configuration changes if possible. For example, with a fresh clone, I was able to run the following:

```
$ cp .env.oss .env.shared
$ cp .env.example .env
$ yarn
$ yarn start
[Force] Building client-side development code...
[Force] Initializing cache...
[Force] Initializing artsyXapp...
[Force] Successfully fetched xapp token.
[Force] Booting on http://localhost:5000
Finished after 7.232 seconds.
```

_Note that I already had Node 14.17.5 and Redis installed._

I saw the following error in the server logs, but it should be safe to ignore and not block the app from running:

```
[Force] Error creating feature flag service: Error: Unleash API "url" is required
    at new Unleash (/Users/devon/code/test/force/node_modules/unleash-client/src/unleash.ts:91:13)
    at initialize (/Users/devon/code/test/force/node_modules/unleash-client/src/index.ts:21:14)
```

<img width="1490" alt="Screen Shot 2022-10-21 at 00 09 01" src="https://user-images.githubusercontent.com/123595/197068477-5f40fa07-f60d-44ff-a6e9-09a92133dfbd.png">

**Comment by dblandin** [comment]
Hi @desaijay315,

Looks like you were hitting one of our firewall block rules. Sorry about that!

I made a minor adjustment to that config and if you try again, that XAPP token fetch should work.

**Comment by desaijay315** [comment]
Okay Sure, I'll try running yarn start

**Comment by desaijay315** [comment]
> Looks like you were hitting one of our firewall block rules. Sorry about that!

Thank you so much for looking into this - Works fine now :)

**Comment by dblandin** [comment]
Glad to hear that!

I'll go ahead and close this issue and thanks again for your interest! 💯

**Comment by desaijay315** [comment]
Thank you so much @dblandin. I really appreciate your help

Can you also redirect me to the list of issues? It seems that Issues are tracked within Jira dashboard. 
How can I get access to the same? I will see if I can pick some of the issues, starting something with low severity, may be :)
