### ISSUE TITLE
Primary artwork image does not reflect settings designated in CMS

### ISSUE THREAD

**Issue by kmpars** [artsy/force#113]
Works are displaying the incorrect primary image both on /collect and on the artwork page. The primary image is correctly set up in CMS but these settings are not reflected on the front end. One example is https://cms.artsy.net/artworks/max-lamb-red-poly-bookcase/images vs.  https://www.artsy.net/artwork/max-lamb-red-poly-bookcase

**Comment by kmpars** [comment]
^ I repositioned the order of images in CMS so the primary image was also the "first" image and this seems to have created the correct ordering on the front end

**Comment by starsirius** [comment]
Thanks for reporting! I believe the images ordering on the /artwork/:id page is [controlled](https://github.com/artsy/force/blob/9b716756ce05380b1c8b8c33782d8c810e4d4dd5/apps/artwork/components/images/index.jade#L5) by the reordering/position set in CMS. I am not entirely sure about the image displayed on /collect page, but I would imagine that's controlled by the "default image" setting of an artwork (maybe @broskoski or someone on the team can confirm).

Also I want to point out that the changes made in CMS may not be reflected immediately on artsy.net, especially the repositioning, due to our caching. Feel free to reach out to the help channel if you think it takes too long to appear so we can take a closer look sooner. 👍

**Comment by alloy** [comment]
@starsirius Can you decide whether or not there’s anything actionable to be done here?

**Comment by starsirius** [comment]
@alloy Created an issue (https://github.com/artsy/volt/issues/2303) in Volt to clarify the difference. Going to close this issue if you give me a 👍 .

**Comment by alloy** [comment]
@starsirius That looks perfect to me 👍
