### ISSUE TITLE
Hack on top MKTO form to fix bug with reload page.

### ISSUE THREAD

**Issue by craigspaeth** [artsy/force#118]
- [x] Bug ~~in MKTO~~ some way we're using MKTO (thanks Dyaln!) where submitting bad data reloads the page and clear out form
- [ ] Focus on first field in form upon debounced scroll or click on form cc @wrgoldstein

**Comment by dylanfareed** [comment]
Took a look at this this am per @jessekedy's request. Force uses the basic embedding code from MKTO. You can see that here as well - http://codepen.io/anon/pen/jrqQPG

The effective issue is that when submitting an invalid embedded form in Force with the default embedded mkto form code, the page reloads rather than being intercepted by the MKTOs error handling. 

The embedded form and error handling works correctly/as expected on that pen. 

Comparing the two there appears to be an extra event listener registered to the Force apply button. The sleuthing is a little odd because of how NR wraps the functions.

![image](https://cloud.githubusercontent.com/assets/197336/18555500/0f506ad8-7b36-11e6-9bd6-5df96c4b36a2.png)

Codepen:

![image](https://cloud.githubusercontent.com/assets/197336/18555516/24182bb8-7b36-11e6-86d5-1918de79037d.png)

Force:

![image](https://cloud.githubusercontent.com/assets/197336/18555534/3b39691a-7b36-11e6-81df-756b4fb685e0.png)

The first of the two listeners in the force screenshot above apparently is pouring sand into the tractor's gas tank here. It's not clear to me where the listener is being registered, but if we remove it through the devtools UI the embedded form error handling works as expected

![image](https://cloud.githubusercontent.com/assets/197336/18555779/1d22db4a-7b37-11e6-8627-195a31e4fb3d.png)

![image](https://cloud.githubusercontent.com/assets/197336/18555831/470deb8e-7b37-11e6-9283-9d3d5163c0ff.png)

Hope this background helps with the resolution.
