### ISSUE TITLE
Gallery Insights Opt-In issues.

### ISSUE THREAD

**Issue by jessekedy** [artsy/force#127]
Adding this issue per Craig's rec.

**Issue 1**: On Gallery Insights pages - when adding an email in the opt-in bar and submitting, the page refreshes and the bar reappears (without the email previously entered). Issues:
1. It's not clear to the user whether they've opted in
2. We should be hiding the opt-in bar for those who have already opted-in

This is a Marketo form, which is likely why this is not working as it was before.

![gif](https://cl.ly/1v3u2H2S1u3k/Screen%20Recording%202016-09-08%20at%2009.54%20AM.gif)

**Issue 2**: The GI opt in page (https://www.artsy.net/gallery-insights/opt-in) is showing this when someone submits the opt-in form.

![opt-in page](https://cl.ly/1k1C3w2I0H1i/Image%202016-09-08%20at%2012.10.12%20PM.png)

cc @kanaabe @craigspaeth

**Comment by alloy** [comment]
@craigspaeth Is this still a thing that needs to be worked on and who’s team is responsible for this?

**Comment by craigspaeth** [comment]
@alloy This is a publishing team item. It appears the issues are still there.

**Comment by craigspaeth** [comment]
@owendodd Please feel free to work with Jesse to fit this in Publishing priorities. I was going to try and take a quick stab at smoothing over the opt-in page issue but it appears we're actually still using Mailchimp there—so probably need some coordinating work with Sara P. or maybe even just drop it altogether b/c this issue is a couple months old and we should probably just build this as a Marketo page now. Closing, but feel free to re-open.
