### ISSUE TITLE
Galleries A-Z page not fetching all the partners

### ISSUE THREAD

**Issue by starsirius** [artsy/force#1800]
Looks like it's capped at 2000 partners.

https://www.artsy.net/galleries-a-z

<img width="1426" alt="screen shot 2017-09-28 at 5 01 40 pm" src="https://user-images.githubusercontent.com/796573/30990348-e85b39ea-a46e-11e7-8865-18065be517c6.png">

**Comment by anandaroop** [comment]
Reported again: https://artsy.slack.com/archives/C03JWJLLH/p1508165922000035

**Comment by anandaroop** [comment]
Looking into this some more…

- There are now >2000 partners eligible for this list
- But we top out at 2000, because we [ask for 20 results per page](https://github.com/artsy/force/blob/master/desktop/apps/galleries_institutions/routes.coffee#L88), and we are limited to 100 pages
- The 100-page limit is [imposed by the partners endpoint](https://github.com/artsy/gravity/blob/master/app/api/v1/partners_endpoint.rb#L169); requests for the 101st page will always fail
- I'm not sure why have that 100-limit (maybe @mzikherman remembers), but I do note that the endpoint goes through Elasticsearch, which [discourages deep paging](https://www.elastic.co/guide/en/elasticsearch/guide/current/pagination.html)

The simplest short-term solution would be to simply bump the page-size, to say 40. That doesn't solve the problem but it would postpone it while we figure out a better solution to this issue (or reconsider the value of an A-Z page which has grown so large)

**Comment by madeleineb** [comment]
Seems like lifting the cap postponed the problem for some time, but now we're back up against the wall with some newly-joined partners not showing up in the list again.

@roop and @starsirius, do you have a sense of whether this is something that could be completed in a half day during bug-bash time, or is it a bigger issue entirely?

**Comment by roop** [comment]
Pinging the right roop: @anandaroop
