### ISSUE TITLE
Miami Fairs Signup Modal

### ISSUE THREAD

**Issue by briansw** [artsy/force#365]
- Required work prior to this issue: https://github.com/artsy/force/issues/169
- Analytics issue to follow
- Display modal for all logged out users that hit the page from outside Artsy:
  - artsy.net/feature/miami-art-week-2016
  - all miami microsites
  - home (?)
- Modal appears after 3 second delay
- Microgravity issue: https://github.com/artsy/microgravity/issues/63
- SVG of X: https://cl.ly/3z1P2e3q0P2e
- Image: https://cl.ly/0b3H3c3E0Y2r
- Stop displaying modals on Dec 5

#### Preview (Nov 16 - Nov 21)
- Header: Get early access to  Miami Art Week
- Copy: Sign up now to preview thousands of artworks and get first access to the best fairs and exhibitions of Miami Art Week

#### Live (Nov 22 - Dec 5)
- Header: Get exclusive access to  Miami Art Week
- Copy: Sign up now to unlock full access to thousands of artworks and get your personalized guide to Miami Art Week

### Flow
![flow](https://cloud.githubusercontent.com/assets/1022172/20072470/8735dfe4-a4f6-11e6-9364-6e05c42bf304.jpg)

### Spec / Responsive behavior
![signup-spec](https://cloud.githubusercontent.com/assets/1022172/20309119/bcca4464-ab14-11e6-8412-fe07d1defa09.jpg)

**Comment by craigspaeth** [comment]
QA
- [ ] Implement responsive behavior on desktop
- [ ] Mobile should be 100% viewport height size instead of the px value it is now
- [ ] Refresh the page after the thank you message on desktop to show logged in
- [ ] Investigate potential performance hit
- [ ] Make sure `acquisition_initiative` is being passed on mobile
- [] only the img panel should resize then eventually pop off
- [] overlay’s z-index should be > auction popups: https://cl.ly/1N0j2r1B2n45
- [] the space after Use in Terms of Use shouldn’t be linked
- [] Privacy Policy should be underlined
- [] terms, privacy, and sign in should be the same color gray as surrounding text
- [] dont make the void space clickable to dismiss the modal (personally against this but think the marketing ppl will want this)
- [] Continue should read “Sign Up”
- [] put focus on email field if possible
- [] X should be `cursor: pointer`

**Comment by anipetrov** [comment]
@craigspaeth did we solve the post social sign up event firing? and the client vs server?

**Comment by craigspaeth** [comment]
@anipetrov We're tracking server-side now which you can tell in the debugger b/c it has this little hexegon JS symbol (stands for Node.js)

![image](https://cloud.githubusercontent.com/assets/555859/20542540/f9593c62-b0cf-11e6-914e-852f22cc8f81.png)

It also contains the "context" and `acquisition_initiative` when clicking through

![image](https://cloud.githubusercontent.com/assets/555859/20542533/f1bd68b6-b0cf-11e6-9bc9-8bc7a7d75758.png)

**Comment by craigspaeth** [comment]
Note: After chatting w/ Ani we should get client-side + server-side tracking in sync, which can take either two routes:

1. Fire the `Created account` client-side event only after successfully signing up (maybe we need Artsy passport to bootstrap something to the client to indicate this? e.g. `res.locals.sd.JUST_SUCESSFULLY_SIGNED_UP = true`)
2. Send all of the data the analytics team would want from the client-side server-side. Which is listed in [this spreadsheet](https://docs.google.com/spreadsheets/u/1/d/1h9sYY1_iYwrjfl4CASP6orxtLe8a2nScvinHYX0tR1Y/edit?usp=sharing). One caveat there is Segment does some non-trivial parsing of things like `context_campaign_medium` is parsed UTM params. Maybe the server-side lib does some lifting for us here though.

This is also a helpful resource for context on _the why_ https://segment.com/academy/collecting-data/when-to-track-on-the-client-vs-server/.

**Comment by anipetrov** [comment]
Thanks so much for the detailed notes, @craigspaeth!

I was wondering, would ad providers like facebook ads and google ads be able to count events for their own internal conversion reporting from server side events? I have not been able to figure it out so far, wondering what your thoughts are.

Also wanted to mention that if we do decide to go forward with both client & server tracking, I think it would be best to set up a new segment project for that (eg force_production_server) so we can keep track of both types of events and not go into complicated naming conventions. 

We can chat more on Monday!

**Comment by anipetrov** [comment]
cc @wrgoldstein @joelauerbach fyi

**Comment by anipetrov** [comment]
Note we are currently sending both server and client events into the `force_production.created_account` table depending on where/how an event was triggered; for some events we only do client, for some we only do server, and for some we fire both. 

Client and server are easily distinguishable since they use different `context_library_name`s: _analytics-node_ for server and _analytics.js_ for client. Thanks to this it should be easy to distinguish between the two but the separate folder project would really help out in this case. We should also make sure that we get full coverage in both cases; we fire the sign up modal in many different contexts and it's getting very hard to be consistent.

**Comment by alloy** [comment]
@craigspaeth Can you take a stab at filing tickets for the QA items that really still need to get done and close this one afterwards?

**Comment by craigspaeth** [comment]
I went ahead and wrapped up the QA work, sending PRs.

**Comment by craigspaeth** [comment]
Closed with https://github.com/artsy/microgravity/pull/70 and https://github.com/artsy/force/pull/472
