### ISSUE TITLE
Forced Signup QA

### ISSUE THREAD

**Issue by briansw** [artsy/force#404]
* [x] Mobile: When trying to create an account I got an error msg: An error occurred, then user already exists. The `created_account` event does fire upond the first attempt. 
    * https://cl.ly/3D0k100x0H1x
    * https://cl.ly/463i2z2N2i3R
* [ ] Mobile: Was able to create an inquiry without logging in
* [x] Mobile: validation turned location field into undefined and any changes to the field would revert to undefined
    * https://cl.ly/0m1K1c0Z1Z0e
* [x] Desktop: location field errors out before any interactions: 
    * https://cl.ly/1a3N051Z3G23
* [x] Desktop: tried to inquire on a pre-qual flow work and used an email with an artsy account. got an error upon sending inquiry (Cab: "Admins are not allowed to place inquiries")
    * https://cl.ly/1n172U043a0W

**Comment by craigspaeth** [comment]
- [ ] Implement responsive behavior on desktop
- [ ] Mobile should be 100% viewport height size instead of the px value it is now
- [ ] Refresh the page after the thank you message on desktop to show logged in
- [ ] Investigate potential performance hit
- [ ] Make sure `acquisition_initiative` is being passed on mobile
