### ISSUE TITLE
Help tooltip text is formatted incorrectly

### ISSUE THREAD

**Issue by briansw** [artsy/force#497]
Looks like:
<img width="585" alt="screen shot 2016-12-09 at 10 11 37 am" src="https://cloud.githubusercontent.com/assets/1022172/21053555/ecf6eb38-bdf7-11e6-9bc2-29980bf1bd06.png">

Should look like help component at bottom of style guide: https://www.artsy.net/style-guide/components

cc @xtina-starr

**Comment by xtina-starr** [comment]
@briansw I changed the location of the tooltip because the inline default get cut off a bit causing the user to have to scroll to the right. Is this okay?

**Before Scroll**
![screen shot 2016-12-09 at 12 33 44 pm](https://cloud.githubusercontent.com/assets/5201004/21058423/e3c6a738-be0b-11e6-81a7-2b15df526993.png)

**After Scroll**
![screen shot 2016-12-09 at 12 34 11 pm](https://cloud.githubusercontent.com/assets/5201004/21058429/e89e17f0-be0b-11e6-857b-a5271cac7760.png)

**Comment by briansw** [comment]
Yeah that works great, was more referring to type size and style. Should be the 17px regular weight style.
