### ISSUE TITLE
Stale UI after login

### ISSUE THREAD

**Issue by 1aurabrown** [artsy/force#621]
@anipetrov saw this happen in the new purchase request flow https://cl.ly/3J0N3Y0m062K. Only on Chrome, on Safari she could not reproduce it.

@kanaabe and @broskoski have seen this happen on just the home page, clearing their cookie made the problem go away, after which they can sign-out and in again without clearing their cookie.

**Comment by alloy** [comment]
I have not been able to reproduce this on Safari and Chrome.

Maybe it’s a specific Chrome version issue? I’m on 54.0.2840.98 (64-bit) and OS X 10.11.6

**Comment by alloy** [comment]
It looks like this is an issue with one of our dependencies having been updated to a version that has an API breaking change that we weren’t handling, specifically we are still using `key` instead of `keys`: https://github.com/expressjs/cookie-session/blob/master/HISTORY.md#200-alpha1--2015-10-11.

We shouldn’t even be using an alpha version of that dependency, though, so we’re reverting to an older version: https://github.com/artsy/force/pull/623
