### ISSUE TITLE
[Artist Signup CTA] Email field validation doesn’t check for TLD

### ISSUE THREAD

**Issue by alloy** [artsy/force#754]
![screen shot 2017-01-24 at 15 06 13](https://cloud.githubusercontent.com/assets/2320/22264620/ac2ba24c-e246-11e6-97bf-41bcb1b0b453.png)

**Comment by alloy** [comment]
TLDs are the Top Level Domains, e.g. `.com`, `.net` etc.

The email validation should probably check that there’s at least a period and suffix in the hostname.

**Comment by tayapage6** [comment]
@alloy do we have a global email validation scheme or are these just one-off form validations?

**Comment by tayapage6** [comment]
Seems like we're at least blocking the sign up if not very gracefully so we're not ending up with users with bad email addresses. not launch critical

**Comment by alloy** [comment]
I’m not sure, @mzikherman can probably better answer re those validation rules.

**Comment by mzikherman** [comment]
We do use mailcheck to offer a hint if it's not a valid email address in the modals triggered from the header. So that can be added to this embedded sign-up form as well?

<img width="437" alt="screen shot 2017-01-24 at 5 47 33 pm" src="https://cloud.githubusercontent.com/assets/1457859/22270379/3c2c367a-e25d-11e6-884c-d486e2475b2f.png">

Note that it's not perfect, and you can still click anyway, but for consistency we could add that 👍

**Comment by kanaabe** [comment]
Hmm def used to do this. There's this issue: https://github.com/mailcheck/mailcheck/issues/139

**Comment by ferreiro** [comment]
yes! the problem is with #133 I mentioned in this PR. i solved it: https://github.com/ZooTools/email-spell-checker/pull/3

----

FYI, I rewrote it entirely and update it for 2022 and onward: https://github.com/ZooTools/email-spell-checker

- 💙 Written in TypeScript and removed jQuery
- ✅ Fixed a couple of bugs like [this](https://github.com/ZooTools/email-spell-checker/pull/3) or [this](https://github.com/ZooTools/email-spell-checker/pull/4)
- 🚀 Reduced bundle size to <2KB. 
- ✨ Update TLDs (69+) and added modern startup domains (like .io, .so, .xyz or .dev)
- 🙏 Implemented suggestions that people made in this repo that were ignored.

Link: https://github.com/ZooTools/email-spell-checker

Come check it out and give it a ⭐️ for the effort.
