### ISSUE TITLE
Artist page signup test: artist names missing/misplaced

### ISSUE THREAD

**Issue by briansw** [artsy/force#783]
@mzikherman @alloy @tayapage6  Hadn't ever come across this issue during QA, but just checked in production and noticed the artist names are missing/misplaced:

![image 2017-01-27 at 9 57 27 am](https://cloud.githubusercontent.com/assets/1022172/22375268/520b79a8-e477-11e6-90ac-735cc42a0914.png)

Also noticing we didn't get that number of artworks change we discussed.

**Comment by mzikherman** [comment]
Weird, yea it looks like that happens when the artist names are really 'short'. I guess we didn't really come across this in QA, but it's reproducible.

I'll look into this today.

Re: the numbers- that issue wasn't logged as a blocker, so it, and some other QA items:

<img width="998" alt="screen shot 2017-01-27 at 10 51 16 am" src="https://cloud.githubusercontent.com/assets/1457859/22377098/914b26ca-e47e-11e6-8759-e70368733c3c.png">

were not done (yet).
