### ISSUE TITLE
"Not for sale" label is showing up for current auctions sometimes

### ISSUE THREAD

**Issue by briansw** [artsy/force#797]
@1aurabrown @tayapage6 it looks like sometimes the "not for sale" label is sneaking in. This particular instance is happening on the home page in the current auction module.

<img width="329" alt="image 2017-02-01 at 11 16 50 am" src="https://cloud.githubusercontent.com/assets/1022172/22515315/1597a468-e870-11e6-931c-8d68c45fb995.png">

**Comment by 1aurabrown** [comment]
@briansw did someone else fix this? i'm not seeing it anymore.

**Comment by briansw** [comment]
No. Maybe it only shows up when there are no bids on the lot? https://cl.ly/3O3M290N2G3H

**Comment by 1aurabrown** [comment]
@briansw, maybe so, good idea i'll try to reproduce it. I think that the bids and the 'sale message' are being displayed independently of one another. so if there is a 'sale message' getting returned from metaphysics that says 'not for sale' it is displayed regardless of whether or not the work is in an auction. i think this isn't a new bug, but perhaps didn't surface before because we weren't displaying detailed (and therefore confilcting) bidder information in this view
