### ISSUE TITLE
"Shows" rail in partner profile overview has non-deterministic sort

### ISSUE THREAD

**Issue by anandaroop** [artsy/force#855]
Raised in Slack: https://artsy.slack.com/archives/partner-s-help/p1487001455004240

On a partner profile overiew page, successive page loads will sometimes yield a different result order for the **Shows** rail, resulting in closed shows appearing at the start of the carousel:

![showsoverview](https://cloud.githubusercontent.com/assets/140521/22906139/37c05e90-f211-11e6-880b-a5c215558a07.gif)

**Comment by 1aurabrown** [comment]
@briansw was this mean to be randomized? i have a feeling this might be intentional. if there is no explicit randomization code these would reliable appear in the same order they're returned from the server. if it's the case that it is intentional, perhaps we can split the shows into two groups, open shows and closed shows, and randomize within each while making sure that the first group always shows up before the second.

**Comment by briansw** [comment]
@1aurabrown @anandaroop Luca worked on this, but it seems like we'd want to prioritize current shows when possible and backfill with upcoming then past when there's room.

**Comment by 1aurabrown** [comment]
@briansw thanks, i'll try to do that.
