### ISSUE TITLE
Add ability to import modules using absolute paths

### ISSUE THREAD

**Issue by damassi** [artsy/force#942]
Since working with relative paths (`../../../`) can be such a pain, we should investigate adding absolute import paths to the pipeline. 

[This Gist](https://gist.github.com/branneman/8048520) outlines four possibilities: 
1. The Symlink
1. The Global
1. The Module
1. The Environment

In my experience I've only used the `NODE_PATH=` environment variable (which worked as expected), but in a complex environment like Force (and possibly Heroku, [though this article seems to suggest it's fine](https://lostechies.com/derickbailey/2014/02/20/how-i-work-around-the-require-problem-in-nodejs/)) there could be problems to investigate. 

The [Browserify Handbook](https://github.com/substack/browserify-handbook#avoiding-) also outlines some options. 

Additionally, since we're using Babel, it would be worth investigating [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver) which compiles down paths into a safe format via a config step. We're currently using this in [in Prediction](https://github.com/artsy/prediction/blob/master/.babelrc#L10).

cc @craigspaeth

**Comment by craigspaeth** [comment]
I like the idea of using NODE_PATH—especially if it integrates nicely with Heroku config and dot env files.

When I've read about this I noticed a lot of people will only [specify one folder](https://gist.github.com/branneman/8048520#gistcomment-972520) as blessed to be added to the path like /lib. I think there's a valid argument there about how using absolute paths across the board makes it less obvious when something might be breaking its "modularity". For instance, I'd like to encourage people to design sub-apps in Force as self-contained slices of functionality behind a set of routes. One should be able to drop apps simply by deleting the folder and taking the line out where it's mounted (e.g. not requiring into other apps). A tangible example of taking advantage of this design is when redesigning a page we'll often "fork" the app (e.g. apps/artist vs. apps/artist2) and delete the loser of the AB test. So maybe it's worth considering absolute requires for project-wide modules like components/lib/models/collections and relative otherwise. 

Tangentially related, I'd also love to hear others thoughts about the folder structure now with Force & MG merged. I think ideally we'd decide to more closely integrate/flatten /desktop and /mobile folders now that the hard merger part is over, and if we change NODE_PATH it could be a good opportunity to switch things up. e.g. if we wanted to bless the lib folder as another "node modules" folder we could consider a structure like...

```
- /apps
  - /artwork
    - /mobile # Pragmatic step towards co-locating MG's app code with Force
    - index.js # Mounts the mobile folder above as a sub-app
- /lib
  - /components
  - /models
  - /collections
  - /middleware
  - /etc
```

Thanks for starting this thread @damassi !!

**Comment by damassi** [comment]
Totally agree about encouraging boundaries for modularity. I think that when a project gets to the size of this one you start to see less interaction between files within a single "app" while heavy interaction outside of it. Looking at `apps/auction/index.coffee` this jumps right out:

```coffeescript
CurrentUser = require '../../../models/current_user.coffee'
Artworks = require '../../../collections/artworks.coffee'
AuctionArtworksView = require '../../../components/auction_artworks/view.coffee'
mediator = require '../../../lib/mediator.coffee'
setupClocks = require './clocks.coffee'
myActiveBidsTemplate = -> require('../templates/my_active_bids.jade') arguments..
EmailRegistrationView = require './email_registration.coffee'
...
```

A quick glance shows us that everything after `./` is within our route, and everything below it is outside of it. Since most of the models and shared components and so on are global, introducing `NODE_PATH` (or something similar) would immediately clean this up and actually make the code _more_ portable and modular since paths unconcerned with the specific route (which generally don't move that far laterally) never have to be touched, regardless of where the module / route / whatever  might move or go. 

Of course, code that's nested into folders inside of a route will eventually have to refer to other code in the route so `../` style paths might still appear, but since the distance is (typically) only one or two levels deep its not so bad. As convention takes hold seeing the `../` would then be an indicator of a much narrower import scope -- it concerns only the files that are specific to our route. 

All that said, I think one of my complaints with relative paths is that it's so rare when looking at the practices of other langs, and thus becomes more of a philosophical question about whats the best way to do things. Since Node's way is something of an outlier, it makes me wonder why other langs typically import off a full package path, and why it's rare to see relative (reverse) imports. The question comes down to which provides more value, because having explicit, absolute path imports provides a lot of metadata about whats going on and might be less error prone than keeping the paths masked (but more portable) via `../foo`.  

Also, +1 for colocating mobile stuff alongside desktop!

**Comment by damassi** [comment]
Another thing I'd like to add about relative path difficulties is project exploration and especially refactoring -- it's difficult to see whats been used where when each path can potentially be different.

**Comment by alloy** [comment]
When evaluating the various options, please also consider how well editors will be able to [open imported files](https://code.visualstudio.com/docs/editor/editingevolved#_go-to-implementation) (i.e. that they can reason about the paths) as well as a language like TypeScript (which basically removes the Babel option), as I’d like 1 solution for all cases.

**Comment by alloy** [comment]
Spoke to an MS employee, they’re using the following combination:

* TS/Intellisense works by specifying the `baseUrl` option in the TS config.
* `babel-plugin-module-resolver` to actually rewrite the paths in the resulting JS.

So the babel plugin would work after all.

**Comment by damassi** [comment]
@alloy - yup, I feel the babel plugin is best as well since it will work seamlessly across the client / server boundary of the stack. 

@craigspaeth - Could we go ahead and give this a spin in Auctions 2? Thoughts?
